### ISSUE TITLE
Unable to import torch

### ISSUE THREAD

**Issue by trdavidson** [JTunis/create-pytorch-lambda-layer#8]
Hi there - thanks for making this project! While I'm able to upload the layer - both directly and through serverless, I am unfortunately not able to import it from a function using the layer failing with:

```
{
  "errorMessage": "Unable to import module 'handler': No module named 'torch'",
  "errorType": "Runtime.ImportModuleError"
}
```

**Comment by JTunis** [comment]
Hey @trdavidson! Are you importing `unzip_requirements` first with something like:

```
try:
    import unzip_requirements
except ImportError:
    pass
import torch
```

**Comment by trdavidson** [comment]
yep!

```
try:
    import unzip_requirements
except ImportError:
    pass
import torch
import json


def handler(event, context):

    print(torch.__version__)
    body = {"pytorch": 'hello!!'}

    return {"statusCode": 200, "body": json.dumps(body)}
```

**Comment by trdavidson** [comment]
Here are the `serverless.yml` files for the function and layer for completion

Function:
```
service: sample-pytorch

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  stage: dev

package:
  exclude:
    - package.json
    - package-lock.json
    - node_modules/**
    - __pycache__/**

functions:
  handler:
    handler: handler.handler
    role: arn:aws:iam::xxxxxx:role/lambda_basic
    layers:
      - arn:aws:lambda:eu-central-1:xxxxxxx:layer:pytorch-layer:1

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
```

Layer:
```
service: pytorch-layer

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  stage: dev

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**
    - __pycache__/**
    - pytorch_layer.zip

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
    strip: false
    noDeploy:
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - setuptools
      - six
      - tensorboard
    useStaticCache: true
    useDownloadCache: true

    layer:
      name: pytorch-layer
      description: pytorch
      package:
        artifact: pytorch_layer.zip
      compatibleRuntimes:
        - python3.8
```
